version: '3.8'

services:
  # Development service
  dev:
    build:
      context: .
      target: build
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - padel-network

  # Production service
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - padel-network
    restart: unless-stopped

networks:
  padel-network:
    driver: bridge 